type Avatar {
    url: String
}

type Settings {
    avatar: Avatar
    isDarkTheme: Boolean
}

type User {
    shortid: String,
    userName: String,
    email: String,
    settings: Settings,
}

type LoginResponse {
    user: User,
    token: String,
    message: String
}

type NewUser {
    user: User,
    message: String,
    token: String
}

type AuthentificationResponse {
    token: String,
    message: String
}

type Query {
    users(token: String!): [User!],
    login(email: String!, password: String!): LoginResponse!,
    authentification(token: String!): AuthentificationResponse!
}

type Mutation {
    createUser(userName: String!, email: String!, password: String!) : NewUser!
}