type User {
    shortid: String,
    userName: String,
    email: String,
    avatar: String,
    createdDate: String
}

type LoginResponse {
    token: String,
    message: String
}

type AuthentificationResponse {
    token: String,
    message: String
}

type CreateUserResponse {
    message: String,
    token: String
}

type AllUsersResponse {
    users: [User!]
    message: String
}

type Query {
    users(token: String!): AllUsersResponse,
    login(email: String!, password: String!): LoginResponse!,
    authentification(token: String!): AuthentificationResponse!
}

type Mutation {
    createUser(userName: String!, email: String!, password: String!) : CreateUserResponse!
}