export const LOGIN = 'AUTH/LOGIN',
             LOGOUT = 'LOGOUT',
             DEFAULT = 'DEFAULT',
             NEW_NOTIFICATION = 'NOTIFICATION/NEW_NOTIFICATION',
             CLEAR_NOTIFICATIONS = 'NOTIFICATION/CLEAR_NOTIFICATIONS',
             TURN_ON_LOADING = 'TURN_ON_LOADING',
             TURN_OFF_LOADING = 'TURN_OFF_LOADING' 
